spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/personal_website
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  security:
    admin:
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}